name: Build

on:
  pull_request:
    types: [ opened ]
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      # リポジトリのチェックアウト
      - name: Checkout Repo
        uses: actions/checkout@v2

      # Node.js のセットアップ
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      # ビルドを実行
      - name: Run build script on package.json
        run: |
          cd functions
          npm install
          npm run build